### PR TITLE
Fixes for 23-407, 23-16, and 22-250

### PR DESCRIPTION
**Pull request by JasonRJFleischer**
Fixes for applicability of 22-250 as changed by 23-16 and 23-407

### CODE REVIEW

**Comment by stonearcher567-beep** [comment]
This looks like a useful set of fixes, especially with the changes affecting applicability and code references. The commit history also makes it easy to follow how the updates evolved. For anyone researching related public information, [Bibb Inmate Records](https://bibbcountyinmatesearch.org/phone-calls-and-mail/) may also be a useful reference. Overall, the changes seem well documented and focused on keeping the implementation accurate.

**Comment by vanghncollier345-cmyk** [comment]
This looks like a solid set of fixes, especially with the updates accounting for changes across multiple law sections. The commit history also makes it easier to see how the applicability instructions evolved during the work. For anyone researching related public information, [Flathead County Jail](https://flatheadcountyjailroster.org/jail-releases/) may also be a useful reference. Overall, the changes appear focused and well documented.

**Comment by max1flex** [comment]
This looks like a solid cleanup of the applicability changes and placeholder updates. The commit history also makes it easy to follow how each legislative change was handled. For anyone reviewing related public records, [Duval County Records](https://duvalcountycourts.org/public-records/) can also be a useful reference point. Nice work keeping the fixes focused and well documented.

**Comment by avamitchell-hash** [comment]
This looks like a useful update, especially with the changes addressing applicability and the related code sections. The detailed commits make it easier to follow what was changed and why. For anyone researching local records, [County Jail Roster](https://crittendencountyjailsar.org/inmate-search/) can also provide useful information in a separate context. Appreciate the clear documentation and concise commit history.

**Pull request merged**
