### PR TITLE
Revert to commit "AppVeyor issue"

### PR DESCRIPTION
**Pull request by JasonRJFleischer**
This Pull Request will revert the repository to commit "AppVeyor issue" (aba8c519c3e3531e569b436dbf2c756fe5cf99c1) before the reversion and when AppVeyor builds were failing.

### CODE REVIEW

**Comment by adellezieme7-hash** [comment]
Reverting a commit can be the cleanest way to restore a stable state when a change causes unexpected issues. It’s also helpful to keep the reason for the revert clear so future contributors have useful context. I find [Kane County Records](https://kanecountycourts.org/public-records/) a useful example of how organized information can make research easier. Hopefully this revert helps get the project back on track.

**Comment by echoflamee867-eng** [comment]
The discussion around reverting to a stable commit makes sense, especially when build issues are affecting development workflows. Keeping a clear record of changes can also make future troubleshooting much easier. For property-related research, I’ve found [DeKalb Property Search](https://dekalbcountypropertyappraiser.org/property-search/) useful for checking organized public property information. Clear documentation like this helps keep projects easier to maintain.

**Comment by lunabreeze042-hue** [comment]
Reverting a problematic commit like this can be a practical way to restore a stable build while the underlying issue is reviewed. I also appreciate how the changes and commit history are clearly documented, which makes it easier to trace what happened. For unrelated research, I recently found [Florida Plate Records](https://florida-license-plates.org/license-plate-basics/) useful for checking publicly available vehicle information. Clear documentation like this makes future maintenance much easier.

**Comment by markustrmbl** [comment]
This is a helpful update, especially for anyone reviewing changes made through a pull request. The detailed commit history makes it easier to follow what was modified and why. I also found [Colorado Plate Information](https://colorado-license-plates.org/plate-costs/) useful for checking related vehicle documentation and general details. Clear records like these make technical and administrative research much easier to follow.

**Pull request merged**
