### PR TITLE
Uncodified 25-237

### PR DESCRIPTION
**Pull request by abyrddccouncil**

### CODE REVIEW

**Comment by ameliajohn9232** [comment]
This update is useful for anyone keeping track of local legislative changes and the status of proposed measures. Having clear records makes it easier to follow amendments, votes, and related documents. For additional information on local filings and case-related records, [Rock County Records](https://rockcountycourt.org/public-records/) can also be a helpful reference. Keeping these details organized makes public information much easier to review.

**Comment by adamrichardson009** [comment]
This is a useful update, especially for keeping the changes organized and easy to review. Clear records and structured information can make it much simpler to verify details when needed. I also found [Pulaski Property Search](https://pulaskicountyassessor.org/property-search/) helpful for reviewing property-related information and records in one place. The approach here looks straightforward and practical for maintaining accurate documentation.

**Comment by gregorysimmons09** [comment]
This is an interesting discussion, especially regarding the value of structured legal data for research and public access. Having reliable information organized clearly can make case-related research much easier for everyone. For those looking into local court information, [Bexar Case Search](https://property-records.bexarcountytx.org/) can also be a useful reference. Clear and accessible records are important for researchers, developers, and members of the public alike.

**Comment by Zileha084** [comment]
I saw that PR #188 trips over the XML deserialization, which triggers the 'error while loading' message you reported. Checking the https://comalcountycourt.org often reveals similar version mismatches that can be used as a sanity check. Adding a fallback for missing nodes will let the UI render even when the external feed is empty. After the fix lands, the CI should clear and reviewers can see the updated legal XML without the reload hiccup.

**Pull request merged**
